# use the official gcc image, based on debian
image: gcc

build-mac:
  stage: build
  script:
    - echo "Building CADventory on `hostname`"
    - echo "artifact from project:$CI_PROJECT_PATH, branch:$CI_COMMIT_BRANCH, job_url:$CI_JOB_URL" > artifact.txt
    # - apt update && apt -y install cmake
    - mkdir .build
    - cd .build && /opt/homebrew/bin/cmake -DQt6_DIR=/opt/homebrew/Cellar/qt/6.6.1/lib/cmake/Qt6 ..
  artifacts:
    paths:
      - artifact.txt
      - cadventory

test:
  stage: test
  script:
    - echo "Testing CADventoryon `hostname`"
    - ls -la
    - ./cadventory

deploy:
  stage: deploy
  script:
    - echo "Deploying CADventory on `hostname`"
  environment: production

