# use the official gcc image, based on debian
image: gcc

stages:
 - build
 - test
 - coverage
 - analyze
 - deploy

build-mac:
  stage: build
  tags:
    - mac
  script:
    - echo "Building CADventory on Mac `hostname` at `pwd`"
    - echo "PATH=$PATH"
    - mkdir .build
    - cd .build
    - echo "compilation artifact from project:$CI_PROJECT_PATH, branch:$CI_COMMIT_BRANCH, job_url:$CI_JOB_URL" > artifact.txt
    - /opt/homebrew/bin/cmake -DCMAKE_PREFIX_PATH=/opt/homebrew/Cellar/qt/6.6.2_1 -DCMAKE_OSX_ARCHITECTURES=arm64 ..
    - make -j4
    - find .
  artifacts:
    paths:
      - .build/artifact.txt
      - .build/cadventory

build-linux:
  stage: build
  tags: 
    - linux
  script:
    - echo "Building CADventory on Linux `hostname` at `pwd`"
    - echo "PATH=$PATH"
    - apt update && apt -y install cmake
    - apt -y install qt6-base-dev sqlite3
    - mkdir .build
    - cd .build
    - echo "compilation artifact from project:$CI_PROJECT_PATH, branch:$CI_COMMIT_BRANCH, job_url:$CI_JOB_URL" > artifact.txt
    - cmake ..
    - make -j4
    - find .
  artifacts:
    paths:
      - .build/artifact.txt
      - .build/cadventory

test-mac:
  stage: test
  tags:
    - mac
  dependencies: 
    - build-mac
  script:
    - echo "Testing CADventory on Mac `hostname` at `pwd`"
    - ls -la
    - find .
    - file .build/cadventory
    - .build/cadventory --no-gui
    - cd .build && ctest --verbose

test-linux:
  stage: test
  tags:
    - linux
  dependencies: 
    - build-linux
  script:
    - echo "Testing CADventory on Linux `hostname` at `pwd`"
    - apt update && apt -y install qt6-base-dev
    - ls -la
    - find .
    - find / -name libQt6Widgets.so.6
    - file .build/cadventory
    - export QT_QPA_PLATFORM=offscreen
    - .build/cadventory --no-gui
    - cd .build && ctest --verbose

coverage-linux:
  stage: coverage
  tags:
    - linux
  dependencies:
    - test-linux
  script:
    - echo "Coverage testing CADventory on Linux `hostname` at `pwd`
    - apt-get update && apt-get install -y lcov
    - cd .build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
    - make clean && make -j2
    - ctest
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system libraries
    - lcov --list coverage.info # For debugging
    - lcov --summary coverage.info
  artifacts:
    paths:
      - build/coverage.info
    expire_in: 1 week
  allow_failure: true

analyze-linux:
  stage: analyze
  tags:
    - linux
  dependencies:
    - test-linux
  script:
    - apt-get update && apt-get install -y clang-tools
    - cd build
    - make clean
    - scan-build make
  allow_failure: true

deploy-mac:
  stage: deploy
  tags:
    - mac
  dependencies: 
    - test-mac
  script:
    - echo "Deploying CADventory on Mac `hostname` at `pwd`"
  environment: production

deploy-linux:
  stage: deploy
  tags:
    - linux
  dependencies: 
    - test-linux
  script:
    - echo "Deploying CADventory on Linux `hostname` at `pwd`"
  environment: production
  