# use the official gcc image, based on debian
image: gcc

build:
  stage: build
  script:
    - echo "Building CADventory"
    - echo "artifact from project:$CI_PROJECT_PATH, branch:$CI_COMMIT_BRANCH, job_url:$CI_JOB_URL" > artifact.txt
    - apt update && apt -y install cmake
    - mkdir .build
    - cd .build && cmake ..
  artifacts:
    paths:
      - artifact.txt
      - cadventory

test:
  stage: test
  script:
    - echo "Testing CADventory"
    - ls -la
    - ./cadventory

deploy:
  stage: deploy
  script:
    - echo "Deploying CADventory"
  environment: production

