# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
- review
- performance
- cleanup

sast:
  stage: test

include:
- template: Auto-DevOps.gitlab-ci.yml

# use the official gcc image, based on debian
image: gcc

build:
  stage: build
  script:
    - apt update && apt -y install cmake
    - g++ helloworld.cpp -o hello
  artifacts:
    paths:
      - hello
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./runmytests.sh

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

